// Code generated by `usage generate go`. DO NOT EDIT.
//
// Binding tables for `oats`, read by
// [github.com/jdx/usage/go/argv]. Regenerate rather than editing: the spec is
// the definition, and a hand-edit here is a difference no reviewer can see.
//
// These are package-level variables holding plain data, so the linker lays them
// out and nothing runs before main.

package usagespec

import (
	"time"

	"github.com/jdx/usage/go/argv"
)

// Keys identify a table entry without a string comparison: switch on the Key an
// event carries rather than on its Name, which is there for diagnostics.
const (
	CmdRoot                 uint64 = 1
	FlagVersion             uint64 = 2
	FlagVerbose             uint64 = 3
	CmdRun                  uint64 = 4
	FlagRunConfig           uint64 = 5
	FlagRunGcx              uint64 = 6
	FlagRunGcxVersion       uint64 = 7
	FlagRunGcxDownload      uint64 = 8
	FlagRunFormat           uint64 = 9
	FlagRunTags             uint64 = 10
	FlagRunTimeout          uint64 = 11
	FlagRunInterval         uint64 = 12
	FlagRunAbsentTimeout    uint64 = 13
	FlagRunSeedSettle       uint64 = 14
	FlagRunGcxContext       uint64 = 15
	FlagRunLgtmVersion      uint64 = 16
	FlagRunContainerRuntime uint64 = 17
	FlagRunAppHost          uint64 = 18
	FlagRunAppPort          uint64 = 19
	FlagRunOtlpHttp         uint64 = 20
	FlagRunParallel         uint64 = 21
	FlagRunFailFast         uint64 = 22
	FlagRunPauseOnFailure   uint64 = 23
	FlagRunNoCache          uint64 = 24
	FlagRunCacheDir         uint64 = 25
	FlagRunList             uint64 = 26
	FlagRunMigrate          uint64 = 27
	ArgRunPaths             uint64 = 28
	CmdList                 uint64 = 29
	FlagListConfig          uint64 = 30
	CmdMigrate              uint64 = 31
	ArgMigratePath          uint64 = 32
	CmdCache                uint64 = 33
	CmdCacheClear           uint64 = 34
	FlagCacheClearCacheDir  uint64 = 35
	CmdVersion              uint64 = 36
	CmdUsage                uint64 = 37
	CmdCompletion           uint64 = 38
	ArgCompletionShell      uint64 = 39
)

// Root is the command tree for `oats`. Pass it to argv.New.
var Root = &argv.Command{
	Name: "oats",
	Key:  CmdRoot,
	Flags: []*argv.Flag{
		{Key: FlagVersion, Name: "version", Longs: []string{"version"}, Shorts: []byte{'V'}, Action: argv.ActionVersion},
		{Key: FlagVerbose, Name: "verbose", Longs: []string{"verbose"}, Shorts: []byte{'v'}, Global: true},
	},
	Subcommands:              []*argv.Command{cmdRun, cmdList, cmdMigrate, cmdCache, cmdVersion, cmdUsage, cmdCompletion},
	UnknownFlags:             argv.UnknownFlagsError,
	DefaultSubcommandFlags:   true,
	DefaultSubcommandOnEmpty: true,
	DefaultSubcommand:        cmdRun,
}

// run
var cmdRun = &argv.Command{
	Name: "run",
	Key:  CmdRun,
	Flags: []*argv.Flag{
		{Key: FlagRunConfig, Name: "config", Longs: []string{"config"}, TakesValue: true},
		{Key: FlagRunGcx, Name: "gcx", Longs: []string{"gcx"}, TakesValue: true},
		{Key: FlagRunGcxVersion, Name: "gcx-version", Longs: []string{"gcx-version"}, TakesValue: true},
		{Key: FlagRunGcxDownload, Name: "gcx-download", Longs: []string{"gcx-download"}, TakesValue: true},
		{Key: FlagRunFormat, Name: "format", Longs: []string{"format"}, TakesValue: true},
		{Key: FlagRunTags, Name: "tags", Longs: []string{"tags"}, TakesValue: true},
		{Key: FlagRunTimeout, Name: "timeout", Longs: []string{"timeout"}, TakesValue: true},
		{Key: FlagRunInterval, Name: "interval", Longs: []string{"interval"}, TakesValue: true},
		{Key: FlagRunAbsentTimeout, Name: "absent-timeout", Longs: []string{"absent-timeout"}, TakesValue: true},
		{Key: FlagRunSeedSettle, Name: "seed-settle", Longs: []string{"seed-settle"}, TakesValue: true},
		{Key: FlagRunGcxContext, Name: "gcx-context", Longs: []string{"gcx-context"}, TakesValue: true},
		{Key: FlagRunLgtmVersion, Name: "lgtm-version", Longs: []string{"lgtm-version"}, TakesValue: true},
		{Key: FlagRunContainerRuntime, Name: "container-runtime", Longs: []string{"container-runtime"}, TakesValue: true},
		{Key: FlagRunAppHost, Name: "app-host", Longs: []string{"app-host"}, TakesValue: true},
		{Key: FlagRunAppPort, Name: "app-port", Longs: []string{"app-port"}, TakesValue: true},
		{Key: FlagRunOtlpHttp, Name: "otlp-http", Longs: []string{"otlp-http"}, TakesValue: true},
		{Key: FlagRunParallel, Name: "parallel", Longs: []string{"parallel"}, TakesValue: true},
		{Key: FlagRunFailFast, Name: "fail-fast", Longs: []string{"fail-fast"}, BoolValue: true},
		{Key: FlagRunPauseOnFailure, Name: "pause-on-failure", Longs: []string{"pause-on-failure"}, BoolValue: true},
		{Key: FlagRunNoCache, Name: "no-cache", Longs: []string{"no-cache"}, BoolValue: true},
		{Key: FlagRunCacheDir, Name: "cache-dir", Longs: []string{"cache-dir"}, TakesValue: true},
		{Key: FlagRunList, Name: "list", Longs: []string{"list"}, BoolValue: true},
		{Key: FlagRunMigrate, Name: "migrate", Longs: []string{"migrate"}, TakesValue: true},
	},
	Args: []*argv.Arg{
		{Key: ArgRunPaths, Name: "paths", Var: true},
	},
	UnknownFlags: argv.UnknownFlagsError,
}

// list
var cmdList = &argv.Command{
	Name: "list",
	Key:  CmdList,
	Flags: []*argv.Flag{
		{Key: FlagListConfig, Name: "config", Longs: []string{"config"}, TakesValue: true},
	},
	UnknownFlags: argv.UnknownFlagsError,
}

// migrate
var cmdMigrate = &argv.Command{
	Name: "migrate",
	Key:  CmdMigrate,
	Args: []*argv.Arg{
		{Key: ArgMigratePath, Name: "path", Required: true},
	},
	UnknownFlags: argv.UnknownFlagsError,
}

// cache
var cmdCache = &argv.Command{
	Name:         "cache",
	Key:          CmdCache,
	Subcommands:  []*argv.Command{cmdCacheClear},
	UnknownFlags: argv.UnknownFlagsError,
}

// cache clear
var cmdCacheClear = &argv.Command{
	Name: "clear",
	Key:  CmdCacheClear,
	Flags: []*argv.Flag{
		{Key: FlagCacheClearCacheDir, Name: "cache-dir", Longs: []string{"cache-dir"}, TakesValue: true},
	},
	UnknownFlags: argv.UnknownFlagsError,
}

// version
var cmdVersion = &argv.Command{
	Name:         "version",
	Key:          CmdVersion,
	UnknownFlags: argv.UnknownFlagsError,
}

// usage
var cmdUsage = &argv.Command{
	Name:         "usage",
	Key:          CmdUsage,
	UnknownFlags: argv.UnknownFlagsError,
}

// completion
var cmdCompletion = &argv.Command{
	Name: "completion",
	Key:  CmdCompletion,
	Args: []*argv.Arg{
		{Key: ArgCompletionShell, Name: "shell", Required: true},
	},
	UnknownFlags: argv.UnknownFlagsError,
}

// Meta is the cold table, read only by the rules that are decided once the
// last token has been read: required, choices, the env-then-default fallback,
// the var bounds, and the four that compare one entry against another. A parse
// never touches it.
//
// Indexed by key, so entry Key sits at Meta[Key-1]. A command's slot is empty:
// commands take keys too, and have no cold half.
var Meta = argv.Metadata{
	{},
	{Key: FlagVersion, Name: "version", Flag: true, RequiresIfBoolean: true, Spelling: "--version"},
	{Key: FlagVerbose, Name: "verbose", Flag: true, RequiresIfBoolean: true, Spelling: "--verbose", Env: "OATS_VERBOSE"},
	{},
	{Key: FlagRunConfig, Name: "config", Flag: true, Spelling: "--config", ValueName: "file", Env: "OATS_CONFIG"},
	{Key: FlagRunGcx, Name: "gcx", Flag: true, Spelling: "--gcx", ValueName: "value", Env: "OATS_GCX"},
	{Key: FlagRunGcxVersion, Name: "gcx-version", Flag: true, Spelling: "--gcx-version", ValueName: "value", Env: "OATS_GCX_VERSION"},
	{Key: FlagRunGcxDownload, Name: "gcx-download", Flag: true, Spelling: "--gcx-download", ValueName: "value", Env: "OATS_GCX_DOWNLOAD"},
	{Key: FlagRunFormat, Name: "format", Flag: true, Spelling: "--format", ValueName: "value", Default: []string{"text"}, Env: "OATS_FORMAT"},
	{Key: FlagRunTags, Name: "tags", Flag: true, Spelling: "--tags", ValueName: "value", Env: "OATS_TAGS"},
	{Key: FlagRunTimeout, Name: "timeout", Flag: true, Spelling: "--timeout", ValueName: "duration", Default: []string{"30s"}, Env: "OATS_TIMEOUT"},
	{Key: FlagRunInterval, Name: "interval", Flag: true, Spelling: "--interval", ValueName: "duration", Default: []string{"500ms"}, Env: "OATS_INTERVAL"},
	{Key: FlagRunAbsentTimeout, Name: "absent-timeout", Flag: true, Spelling: "--absent-timeout", ValueName: "duration", Default: []string{"10s"}, Env: "OATS_ABSENT_TIMEOUT"},
	{Key: FlagRunSeedSettle, Name: "seed-settle", Flag: true, Spelling: "--seed-settle", ValueName: "duration", Default: []string{"2s"}, Env: "OATS_SEED_SETTLE"},
	{Key: FlagRunGcxContext, Name: "gcx-context", Flag: true, Spelling: "--gcx-context", ValueName: "value", Env: "OATS_GCX_CONTEXT"},
	{Key: FlagRunLgtmVersion, Name: "lgtm-version", Flag: true, Spelling: "--lgtm-version", ValueName: "value", Env: "OATS_LGTM_VERSION"},
	{Key: FlagRunContainerRuntime, Name: "container-runtime", Flag: true, Spelling: "--container-runtime", ValueName: "value", Default: []string{"auto"}, Env: "OATS_CONTAINER_RUNTIME"},
	{Key: FlagRunAppHost, Name: "app-host", Flag: true, Spelling: "--app-host", ValueName: "value", Default: []string{"localhost"}, Env: "OATS_APP_HOST"},
	{Key: FlagRunAppPort, Name: "app-port", Flag: true, Spelling: "--app-port", ValueName: "number", Default: []string{"8080"}, Env: "OATS_APP_PORT"},
	{Key: FlagRunOtlpHttp, Name: "otlp-http", Flag: true, Spelling: "--otlp-http", ValueName: "value", Default: []string{"http://127.0.0.1:4318"}, Env: "OATS_OTLP_HTTP"},
	{Key: FlagRunParallel, Name: "parallel", Flag: true, Spelling: "--parallel", ValueName: "number", Default: []string{"1"}, Env: "OATS_PARALLEL"},
	{Key: FlagRunFailFast, Name: "fail-fast", Flag: true, RequiresIfBoolean: true, Spelling: "--fail-fast", Env: "OATS_FAIL_FAST"},
	{Key: FlagRunPauseOnFailure, Name: "pause-on-failure", Flag: true, RequiresIfBoolean: true, Spelling: "--pause-on-failure", Env: "OATS_PAUSE_ON_FAILURE"},
	{Key: FlagRunNoCache, Name: "no-cache", Flag: true, RequiresIfBoolean: true, Spelling: "--no-cache", Env: "OATS_NO_CACHE"},
	{Key: FlagRunCacheDir, Name: "cache-dir", Flag: true, Spelling: "--cache-dir", ValueName: "dir", Env: "OATS_CACHE_DIR"},
	{Key: FlagRunList, Name: "list", Flag: true, RequiresIfBoolean: true, Spelling: "--list", Env: "OATS_LIST"},
	{Key: FlagRunMigrate, Name: "migrate", Flag: true, Spelling: "--migrate", ValueName: "value", Env: "OATS_MIGRATE"},
	{Key: ArgRunPaths, Name: "paths"},
	{},
	{Key: FlagListConfig, Name: "config", Flag: true, Spelling: "--config", ValueName: "file", Env: "OATS_CONFIG"},
	{},
	{Key: ArgMigratePath, Name: "path", Required: true},
	{},
	{},
	{Key: FlagCacheClearCacheDir, Name: "cache-dir", Flag: true, Spelling: "--cache-dir", ValueName: "dir", Env: "OATS_CACHE_DIR"},
	{},
	{},
	{},
	{Key: ArgCompletionShell, Name: "shell", Required: true, Choices: []string{"bash", "zsh", "fish", "powershell", "nu"}, AcceptedChoices: []string{"bash", "zsh", "fish", "powershell", "nu"}},
}

// HelpText is the third table, read only when a page is rendered. Neither the
// parser nor the post-binding rules touch it, and a CLI that never prints help
// does not carry it: Go's linker drops an unreferenced table whole.
//
// Indexed by key, like the others.
var HelpText = argv.HelpTable{
	{Key: CmdRoot},
	{Key: FlagVersion, Short: "Print the oats version", Long: "Print the oats version"},
	{Key: FlagVerbose, Short: "increase verbosity (-v, -vv, -vvv)", Long: "increase verbosity (-v, -vv, -vvv)", Env: "OATS_VERBOSE"},
	{Key: CmdRun, Short: "Run cases (also the default without a subcommand)"},
	{Key: FlagRunConfig, ValueName: "file", ValueDemanded: true, Short: "path to oats-config.yaml", Long: "path to oats-config.yaml", Env: "OATS_CONFIG"},
	{Key: FlagRunGcx, ValueName: "value", ValueDemanded: true, Short: "path to gcx binary (PATH-resolved if a bare name)", Long: "path to gcx binary (PATH-resolved if a bare name)", Env: "OATS_GCX"},
	{Key: FlagRunGcxVersion, ValueName: "value", ValueDemanded: true, Short: "download and use this gcx release", Long: "download and use this gcx release", Env: "OATS_GCX_VERSION"},
	{Key: FlagRunGcxDownload, ValueName: "value", ValueDemanded: true, Short: "gcx fallback download policy (auto; never under mise)", Long: "gcx fallback download policy (auto; never under mise)", Env: "OATS_GCX_DOWNLOAD"},
	{Key: FlagRunFormat, ValueName: "value", ValueDemanded: true, Short: "output format: text | ndjson", Long: "output format: text | ndjson", Env: "OATS_FORMAT", Default: []string{"text"}},
	{Key: FlagRunTags, ValueName: "value", ValueDemanded: true, Short: "comma-separated tag any-match", Long: "comma-separated tag any-match", Env: "OATS_TAGS"},
	{Key: FlagRunTimeout, ValueName: "duration", ValueDemanded: true, Short: "per-assertion timeout", Long: "per-assertion timeout", Env: "OATS_TIMEOUT", Default: []string{"30s"}},
	{Key: FlagRunInterval, ValueName: "duration", ValueDemanded: true, Short: "polling interval", Long: "polling interval", Env: "OATS_INTERVAL", Default: []string{"500ms"}},
	{Key: FlagRunAbsentTimeout, ValueName: "duration", ValueDemanded: true, Short: "how long an absent assertion must stay absent", Long: "how long an absent assertion must stay absent", Env: "OATS_ABSENT_TIMEOUT", Default: []string{"10s"}},
	{Key: FlagRunSeedSettle, ValueName: "duration", ValueDemanded: true, Short: "post-seed wait before first assertion", Long: "post-seed wait before first assertion", Env: "OATS_SEED_SETTLE", Default: []string{"2s"}},
	{Key: FlagRunGcxContext, ValueName: "value", ValueDemanded: true, Short: "override the gcx --context value (otherwise derived from fixture endpoint)", Long: "override the gcx --context value (otherwise derived from fixture endpoint)", Env: "OATS_GCX_CONTEXT"},
	{Key: FlagRunLgtmVersion, ValueName: "value", ValueDemanded: true, Short: "version of docker.io/grafana/otel-lgtm used by the builtin Compose fixture", Long: "version of docker.io/grafana/otel-lgtm used by the builtin Compose fixture", Env: "OATS_LGTM_VERSION"},
	{Key: FlagRunContainerRuntime, ValueName: "value", ValueDemanded: true, Short: "container engine for Compose fixtures: auto | docker | podman", Long: "container engine for Compose fixtures: auto | docker | podman", Env: "OATS_CONTAINER_RUNTIME", Default: []string{"auto"}},
	{Key: FlagRunAppHost, ValueName: "value", ValueDemanded: true, Short: "application host for driving case input requests", Long: "application host for driving case input requests", Env: "OATS_APP_HOST", Default: []string{"localhost"}},
	{Key: FlagRunAppPort, ValueName: "number", ValueDemanded: true, Short: "application port for driving case input requests", Long: "application port for driving case input requests", Env: "OATS_APP_PORT", Default: []string{"8080"}},
	{Key: FlagRunOtlpHttp, ValueName: "value", ValueDemanded: true, Short: "OTLP/HTTP base URL for inline-otlp seed mode", Long: "OTLP/HTTP base URL for inline-otlp seed mode", Env: "OATS_OTLP_HTTP", Default: []string{"http://127.0.0.1:4318"}},
	{Key: FlagRunParallel, ValueName: "number", ValueDemanded: true, Short: "number of fixture groups to run in parallel when fixture isolation allows it", Long: "number of fixture groups to run in parallel when fixture isolation allows it", Env: "OATS_PARALLEL", Default: []string{"1"}},
	{Key: FlagRunFailFast, Short: "stop scheduling further cases after the first case failure", Long: "stop scheduling further cases after the first case failure", Env: "OATS_FAIL_FAST"},
	{Key: FlagRunPauseOnFailure, Short: "retain one managed Compose fixture after the first failure for interactive gcx diagnosis", Long: "retain one managed Compose fixture after the first failure for interactive gcx diagnosis", Env: "OATS_PAUSE_ON_FAILURE"},
	{Key: FlagRunNoCache, Short: "disable the skip-when-unchanged cache for this run", Long: "disable the skip-when-unchanged cache for this run", Env: "OATS_NO_CACHE"},
	{Key: FlagRunCacheDir, ValueName: "dir", ValueDemanded: true, Short: "cache directory (defaults to the user state directory)", Long: "cache directory (defaults to the user state directory)", Env: "OATS_CACHE_DIR"},
	{Key: FlagRunList, Hide: true, Short: "deprecated: use `oats list`", Long: "deprecated: use `oats list`", Env: "OATS_LIST"},
	{Key: FlagRunMigrate, Hide: true, ValueName: "value", ValueDemanded: true, Short: "deprecated: use `oats migrate <file>`", Long: "deprecated: use `oats migrate <file>`", Env: "OATS_MIGRATE"},
	{Key: ArgRunPaths, Short: "case paths, or a config/project path when no config is discovered", Long: "case paths, or a config/project path when no config is discovered"},
	{Key: CmdList, Short: "Print the run plan without execution"},
	{Key: FlagListConfig, ValueName: "file", ValueDemanded: true, Short: "path to oats-config.yaml", Long: "path to oats-config.yaml", Env: "OATS_CONFIG"},
	{Key: CmdMigrate, Short: "Convert a legacy file to stdout, or migrate a directory in place"},
	{Key: ArgMigratePath, Demanded: true, Short: "legacy YAML file or directory", Long: "legacy YAML file or directory"},
	{Key: CmdCache, Short: "Manage the skip-when-unchanged cache"},
	{Key: CmdCacheClear, Short: "Delete all cached results"},
	{Key: FlagCacheClearCacheDir, ValueName: "dir", ValueDemanded: true, Short: "cache directory (defaults to the user state directory)", Long: "cache directory (defaults to the user state directory)", Env: "OATS_CACHE_DIR"},
	{Key: CmdVersion, Short: "Print the oats version"},
	{Key: CmdUsage, Short: "Print the Usage specification"},
	{Key: CmdCompletion, Short: "Generate shell completions"},
	{Key: ArgCompletionShell, Demanded: true, Short: "shell to configure", Long: "shell to configure", Choices: []string{"bash", "zsh", "fish", "powershell", "nu"}},
}

// HelpMeta is what a page needs from the spec's root rather than from any one
// command: root presentation metadata and CLI-wide layout.
var HelpMeta = argv.HelpSpec{Name: "oats", Bin: "oats", About: "OpenTelemetry Acceptance Tests — the gcx-driven runner"}

// Cli is the whole command line.
type Cli struct {
	Version    bool           // FlagVersion
	Verbose    int            // FlagVerbose
	Run        *RunCmd        // CmdRun
	List       *ListCmd       // CmdList
	Migrate    *MigrateCmd    // CmdMigrate
	Cache      *CacheCmd      // CmdCache
	VersionCmd *VersionCmd    // CmdVersion
	Usage      *UsageCmd      // CmdUsage
	Completion *CompletionCmd // CmdCompletion
}

// RunCmd is `run`.
type RunCmd struct {
	Config           string        // FlagRunConfig
	Gcx              string        // FlagRunGcx
	GcxVersion       string        // FlagRunGcxVersion
	GcxDownload      string        // FlagRunGcxDownload
	Format           string        // FlagRunFormat
	Tags             string        // FlagRunTags
	Timeout          time.Duration // FlagRunTimeout
	Interval         time.Duration // FlagRunInterval
	AbsentTimeout    time.Duration // FlagRunAbsentTimeout
	SeedSettle       time.Duration // FlagRunSeedSettle
	GcxContext       string        // FlagRunGcxContext
	LgtmVersion      string        // FlagRunLgtmVersion
	ContainerRuntime string        // FlagRunContainerRuntime
	AppHost          string        // FlagRunAppHost
	AppPort          int           // FlagRunAppPort
	OtlpHttp         string        // FlagRunOtlpHttp
	Parallel         int           // FlagRunParallel
	FailFast         bool          // FlagRunFailFast
	PauseOnFailure   bool          // FlagRunPauseOnFailure
	NoCache          bool          // FlagRunNoCache
	CacheDir         string        // FlagRunCacheDir
	List             bool          // FlagRunList
	Migrate          string        // FlagRunMigrate
	Paths            []string      // ArgRunPaths
}

// ListCmd is `list`.
type ListCmd struct {
	Config string // FlagListConfig
}

// MigrateCmd is `migrate`.
type MigrateCmd struct {
	Path string // ArgMigratePath
}

// CacheCmd is `cache`.
type CacheCmd struct {
	Clear *CacheClearCmd // CmdCacheClear
}

// CacheClearCmd is `cache clear`.
type CacheClearCmd struct {
	CacheDir string // FlagCacheClearCacheDir
}

// VersionCmd is `version`.
type VersionCmd struct{}

// UsageCmd is `usage`.
type UsageCmd struct{}

// CompletionCmd is `completion`.
type CompletionCmd struct {
	Shell string // ArgCompletionShell
}

// Parse binds a command line and fills the structs above.
//
// The rules decided once the last token has been read run here too, so a
// missing required flag or a value outside its choices comes back rather than
// reaching your code. A returned error is an *argv.Error; render it with
// argv.Render.
//
// Help and version arrive as errors, because a parse that stops to print a page
// has produced no value. Check the code before treating one as a failure.
func Parse(args []string) (*Cli, error) {
	out := &Cli{}
	var cmdRunV *RunCmd
	var cmdListV *ListCmd
	var cmdMigrateV *MigrateCmd
	var cmdCacheV *CacheCmd
	var cmdCacheClearV *CacheClearCmd
	var cmdVersionV *VersionCmd
	var cmdUsageV *UsageCmd
	var cmdCompletionV *CompletionCmd

	// Collected by key, so the post-binding rules can judge what arrived
	// before any of it is handed back.
	given := map[uint64][]string{}
	seen := map[uint64]int{}
	chain := []*argv.Command{Root}

	p := argv.New(Root, args)
	for p.Next() {
		ev := p.Event()
		switch ev.Kind {
		case argv.KindCommand:
			chain = append(chain, ev.Command)
			switch ev.Command.Key {
			case CmdRun:
				cmdRunV = &RunCmd{}
				out.Run = cmdRunV
			case CmdList:
				cmdListV = &ListCmd{}
				out.List = cmdListV
			case CmdMigrate:
				cmdMigrateV = &MigrateCmd{}
				out.Migrate = cmdMigrateV
			case CmdCache:
				cmdCacheV = &CacheCmd{}
				out.Cache = cmdCacheV
			case CmdCacheClear:
				cmdCacheClearV = &CacheClearCmd{}
				cmdCacheV.Clear = cmdCacheClearV
			case CmdVersion:
				cmdVersionV = &VersionCmd{}
				out.VersionCmd = cmdVersionV
			case CmdUsage:
				cmdUsageV = &UsageCmd{}
				out.Usage = cmdUsageV
			case CmdCompletion:
				cmdCompletionV = &CompletionCmd{}
				out.Completion = cmdCompletionV
			}
		case argv.KindFlag:
			// The event parser leaves synthetic help/version requests to its caller.
			switch ev.Flag {
			case argv.HelpShort, argv.HelpLong:
				return nil, &argv.Error{Code: argv.CodeHelp, Cmd: p.Command(), Long: ev.Flag == argv.HelpLong}
			case argv.VersionShort, argv.VersionLong:
				return nil, &argv.Error{Code: argv.CodeVersion, Cmd: p.Command(), Long: ev.Flag == argv.VersionLong}
			}
			seen[ev.Flag.Key]++
			if ev.Flag.BoolValue {
				// Boolean binding is last-one-wins. Replace an earlier attached value even
				// when the last occurrence is bare, so relationship polarity follows the field.
				if ev.HasValue {
					given[ev.Flag.Key] = []string{ev.Value}
				} else {
					given[ev.Flag.Key] = []string{}
				}
			} else if ev.HasValue {
				given[ev.Flag.Key] = append(given[ev.Flag.Key], argv.SplitValue(ev.Value, ev.Flag.Delimiter, true)...)
			} else if given[ev.Flag.Key] == nil {
				// Given without a value is still given, and nil would read as
				// absent when the fallbacks are applied.
				given[ev.Flag.Key] = []string{}
			}
			switch ev.Flag.Key {
			case FlagVersion:
				out.Version = !ev.Negated
			case FlagVerbose:
				out.Verbose++
			case FlagRunConfig:
				cmdRunV.Config = ev.Value
			case FlagRunGcx:
				cmdRunV.Gcx = ev.Value
			case FlagRunGcxVersion:
				cmdRunV.GcxVersion = ev.Value
			case FlagRunGcxDownload:
				cmdRunV.GcxDownload = ev.Value
			case FlagRunFormat:
				cmdRunV.Format = ev.Value
			case FlagRunTags:
				cmdRunV.Tags = ev.Value
			case FlagRunGcxContext:
				cmdRunV.GcxContext = ev.Value
			case FlagRunLgtmVersion:
				cmdRunV.LgtmVersion = ev.Value
			case FlagRunContainerRuntime:
				cmdRunV.ContainerRuntime = ev.Value
			case FlagRunAppHost:
				cmdRunV.AppHost = ev.Value
			case FlagRunOtlpHttp:
				cmdRunV.OtlpHttp = ev.Value
			case FlagRunFailFast:
				if ev.HasValue {
					cmdRunV.FailFast = (ev.Value == "true") != ev.Negated
				} else {
					cmdRunV.FailFast = !ev.Negated
				}
			case FlagRunPauseOnFailure:
				if ev.HasValue {
					cmdRunV.PauseOnFailure = (ev.Value == "true") != ev.Negated
				} else {
					cmdRunV.PauseOnFailure = !ev.Negated
				}
			case FlagRunNoCache:
				if ev.HasValue {
					cmdRunV.NoCache = (ev.Value == "true") != ev.Negated
				} else {
					cmdRunV.NoCache = !ev.Negated
				}
			case FlagRunCacheDir:
				cmdRunV.CacheDir = ev.Value
			case FlagRunList:
				if ev.HasValue {
					cmdRunV.List = (ev.Value == "true") != ev.Negated
				} else {
					cmdRunV.List = !ev.Negated
				}
			case FlagRunMigrate:
				cmdRunV.Migrate = ev.Value
			case FlagListConfig:
				cmdListV.Config = ev.Value
			case FlagCacheClearCacheDir:
				cmdCacheClearV.CacheDir = ev.Value
			}
		case argv.KindArg:
			seen[ev.Arg.Key]++
			values := argv.SplitValue(ev.Value, ev.Arg.Delimiter, ev.Delimit)
			given[ev.Arg.Key] = append(given[ev.Arg.Key], values...)
			switch ev.Arg.Key {
			case ArgRunPaths:
				cmdRunV.Paths = append(cmdRunV.Paths, values...)
			case ArgMigratePath:
				cmdMigrateV.Path = ev.Value
			case ArgCompletionShell:
				cmdCompletionV.Shell = ev.Value
			}
		}
	}
	if err := p.Err(); err != nil {
		return nil, err
	}
	if p.Command().ArgRequiredElseHelp && p.CommandStart() == len(args) {
		return nil, &argv.Error{Code: argv.CodeHelp, Cmd: p.Command()}
	}

	// Only the commands the words actually selected are judged: a required
	// flag on a command nobody ran is not missing.
	var scope []uint64
	requirements := map[uint64]bool{}
	for i, cmd := range chain {
		checkRequirements := i == len(chain)-1 || !cmd.SubcommandNegatesReqs
		for _, f := range cmd.Flags {
			scope = append(scope, f.Key)
			requirements[f.Key] = checkRequirements
		}
		for _, a := range cmd.Args {
			scope = append(scope, a.Key)
			requirements[a.Key] = checkRequirements
		}
	}
	sources := map[uint64]argv.Source{}
	filled := map[uint64][]string{}
	for _, key := range scope {
		values, source := argv.Fill(Meta.Lookup(key), given[key], argv.LookupEnv)
		filled[key] = values
		sources[key] = source
	}
	argv.ApplyDefaultIf(Meta, scope, filled, sources, nil)
	for _, key := range scope {
		values, source := filled[key], sources[key]
		entryMeta := Meta.Lookup(key)
		if entryMeta != nil && !requirements[key] {
			copy := *entryMeta
			copy.Required = false
			entryMeta = &copy
		}
		if err := argv.Check(entryMeta, values, seen[key]); err != nil {
			return nil, err
		}
		// What the environment or a default supplied has to reach the field
		// too. A front door that enforces a default and then hands back the
		// zero value is worse than one that has no defaults at all.
		//
		// Written here rather than in a function of its own because a
		// subcommand's struct is reachable only from inside this one: the
		// variable holding it is local, and only the keys of commands the
		// words selected are in scope, so it is never nil when its key is.
		if source == argv.FromEnv || source == argv.FromDefault {
			switch key {
			case FlagVersion:
				if source == argv.FromEnv {
					out.Version = argv.EnvTruth(values[0])
				} else {
					out.Version = values[0] == "true"
				}
			case FlagRunConfig:
				cmdRunV.Config = values[len(values)-1]
			case FlagRunGcx:
				cmdRunV.Gcx = values[len(values)-1]
			case FlagRunGcxVersion:
				cmdRunV.GcxVersion = values[len(values)-1]
			case FlagRunGcxDownload:
				cmdRunV.GcxDownload = values[len(values)-1]
			case FlagRunFormat:
				cmdRunV.Format = values[len(values)-1]
			case FlagRunTags:
				cmdRunV.Tags = values[len(values)-1]
			case FlagRunGcxContext:
				cmdRunV.GcxContext = values[len(values)-1]
			case FlagRunLgtmVersion:
				cmdRunV.LgtmVersion = values[len(values)-1]
			case FlagRunContainerRuntime:
				cmdRunV.ContainerRuntime = values[len(values)-1]
			case FlagRunAppHost:
				cmdRunV.AppHost = values[len(values)-1]
			case FlagRunOtlpHttp:
				cmdRunV.OtlpHttp = values[len(values)-1]
			case FlagRunFailFast:
				if source == argv.FromEnv {
					cmdRunV.FailFast = argv.EnvTruth(values[0])
				} else {
					cmdRunV.FailFast = values[0] == "true"
				}
			case FlagRunPauseOnFailure:
				if source == argv.FromEnv {
					cmdRunV.PauseOnFailure = argv.EnvTruth(values[0])
				} else {
					cmdRunV.PauseOnFailure = values[0] == "true"
				}
			case FlagRunNoCache:
				if source == argv.FromEnv {
					cmdRunV.NoCache = argv.EnvTruth(values[0])
				} else {
					cmdRunV.NoCache = values[0] == "true"
				}
			case FlagRunCacheDir:
				cmdRunV.CacheDir = values[len(values)-1]
			case FlagRunList:
				if source == argv.FromEnv {
					cmdRunV.List = argv.EnvTruth(values[0])
				} else {
					cmdRunV.List = values[0] == "true"
				}
			case FlagRunMigrate:
				cmdRunV.Migrate = values[len(values)-1]
			case ArgRunPaths:
				cmdRunV.Paths = append(cmdRunV.Paths, values...)
			case FlagListConfig:
				cmdListV.Config = values[len(values)-1]
			case ArgMigratePath:
				cmdMigrateV.Path = values[len(values)-1]
			case FlagCacheClearCacheDir:
				cmdCacheClearV.CacheDir = values[len(values)-1]
			case ArgCompletionShell:
				cmdCompletionV.Shell = values[len(values)-1]
			}
		}
	}
	if err := argv.CheckRelationshipsWithValuesAndRequirements(Meta, scope, func(k uint64) argv.Source {
		return sources[k]
	}, nil, func(k uint64) bool { return requirements[k] }); err != nil {
		return nil, err
	}
	if values := filled[FlagRunTimeout]; len(values) > 0 {
		value, err := argv.Duration("--timeout", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.Timeout = value
	}
	if values := filled[FlagRunInterval]; len(values) > 0 {
		value, err := argv.Duration("--interval", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.Interval = value
	}
	if values := filled[FlagRunAbsentTimeout]; len(values) > 0 {
		value, err := argv.Duration("--absent-timeout", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.AbsentTimeout = value
	}
	if values := filled[FlagRunSeedSettle]; len(values) > 0 {
		value, err := argv.Duration("--seed-settle", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.SeedSettle = value
	}
	if values := filled[FlagRunAppPort]; len(values) > 0 {
		value, err := argv.NativeInt("--app-port", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.AppPort = value
	}
	if values := filled[FlagRunParallel]; len(values) > 0 {
		value, err := argv.NativeInt("--parallel", values[len(values)-1])
		if err != nil {
			return nil, err
		}
		cmdRunV.Parallel = value
	}
	return out, nil
}
