# Lychee configuration file
# See https://lychee.cli.rs/config/

timeout = 30
retry_wait_time = 10
max_retries = 2
max_concurrency = 4

# Check link anchors
include_fragments = "anchor-only"

exclude = [
  # Google Docs links are often rate-limited
  "https://docs.google.com/.*",
]
