version: '3.8'

services:
  # Go based test server
  testserver:
    image: grcevski/tests:gotestserver
    container_name: hatest-testserver
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "50051:50051"
    environment:
      LOG_LEVEL: DEBUG

  # eBPF auto instrumenter
  autoinstrumenter:
    image: grafana/ebpf-autoinstrument:latest
    command:
      - /otelauto
      - --config=/configs/instrumenter-config-traces.yml
    volumes:
      - ./configs/:/configs
      - ./testoutput/run:/var/run/otelauto
    container_name: hatest-autoinstrumenter
    privileged: true # in some environments (not GH Pull Requests) you can set it to false and then cap_add: [ SYS_ADMIN ]
    network_mode: "service:testserver"
    pid: "service:testserver"
    environment:
      PRINT_TRACES: "true"
      OPEN_PORT: "8080"
      SERVICE_NAMESPACE: "integration-test"
      METRICS_INTERVAL: "10ms"
      BPF_BATCH_TIMEOUT: "10ms"
      LOG_LEVEL: "DEBUG"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://agent:4018/v1/traces"
    depends_on:
      testserver:
        condition: service_started

  # Agent
  agent:
    image: grafana/agent
    container_name: hatest-agent
    command:
      - run
      - /etc/agent/agent-config.river
    volumes:
      - ./configs/:/etc/agent
    environment:
      AGENT_MODE: "flow"
    ports:
      - "4017:4017"
      - "4018:4018"

  # Tempo
  tempo:
    image: grafana/tempo
    container_name: hatest-tempo
    command:
      - -config.file 
      - /etc/tempo/tempo-config.yaml
    volumes:
      - ./configs/:/etc/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
