# Do not use this configuration in production.
# It is for demonstration purposes only.
# metrics_generator_enabled: true
# search_enabled: true

server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

metrics_generator:
  ring:
    kvstore: {}
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
